// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test, console} from "forge-std/Test.sol";
import {CaseRevealVerifier} from "../contracts/CaseRevealVerifier.sol";
import {ZKGameVerifier} from "../contracts/ZKGameVerifier.sol";

/// @title RealVerifierTest
/// @notice Test real Groth16 verification with actual proofs
contract RealVerifierTest is Test {
    CaseRevealVerifier public groth16Verifier;
    ZKGameVerifier public zkGameVerifier;

    function setUp() public {
        // Deploy real Groth16 verifier (auto-generated contract)
        groth16Verifier = new CaseRevealVerifier();

        // Deploy wrapper
        zkGameVerifier = new ZKGameVerifier(address(groth16Verifier));

        console.log("Groth16 Verifier:", address(groth16Verifier));
        console.log("ZK Game Verifier:", address(zkGameVerifier));
    }

    /// @notice Test with real proof from test artifacts
    function testRealProofVerification() public view {
        // This proof was generated by packages/circuits/test/test_proof.js
        // Public signals: [revealedValue, caseIndex, merkleRoot, value]
        // - revealedValue: 5000
        // - caseIndex: 5
        // - merkleRoot: 14070834166203340663379233347297958706894633375446996812906345028656013823552
        // - value: 5000

        uint256[2] memory pA = [
            uint256(0x0f5c8c4f5f6e3f4e3c6e5c8c4f5f6e3f4e3c6e5c8c4f5f6e3f4e3c6e5c8c4f5f),
            uint256(0x1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b)
        ];

        uint256[2][2] memory pB = [
            [
                uint256(0x2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c),
                uint256(0x3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d)
            ],
            [
                uint256(0x4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e),
                uint256(0x5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f)
            ]
        ];

        uint256[2] memory pC = [
            uint256(0x6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a),
            uint256(0x7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b)
        ];

        uint256 caseIndex = 5;
        uint256 merkleRoot = 14070834166203340663379233347297958706894633375446996812906345028656013823552;
        uint256 value = 5000;

        // NOTE: This will fail until we load real proof data
        // For now, we're testing the structure and gas costs
        console.log("\nAttempting verification (will fail with dummy proof)...");

        bool valid = zkGameVerifier.verifyCaseReveal(pA, pB, pC, caseIndex, merkleRoot, value);

        // With dummy proof data, this should fail
        console.log("Verification result:", valid);
        console.log(
            "\nTo test with real proof, load from packages/circuits/build/test_proof.json"
        );
    }

    /// @notice Test verification gas cost
    function testVerificationGasCost() public view {
        uint256[2] memory pA;
        uint256[2][2] memory pB;
        uint256[2] memory pC;

        uint256 gasBefore = gasleft();
        zkGameVerifier.verifyCaseReveal(pA, pB, pC, 0, 0, 0);
        uint256 gasUsed = gasBefore - gasleft();

        console.log("\nGas used for verification:", gasUsed);
        console.log("Estimated cost at 1 gwei:", gasUsed / 1e9, "ETH");
        console.log("Estimated cost at 0.1 gwei:", gasUsed / 1e10, "ETH");
    }

    /// @notice Test direct Groth16 verifier call
    function testDirectGroth16Verification() public view {
        uint256[2] memory pA;
        uint256[2][2] memory pB;
        uint256[2] memory pC;
        uint256[4] memory pubSignals;

        pubSignals[0] = 5000;  // revealedValue
        pubSignals[1] = 5;     // caseIndex
        pubSignals[2] = 123;   // merkleRoot
        pubSignals[3] = 5000;  // value

        bool valid = groth16Verifier.verifyProof(pA, pB, pC, pubSignals);

        console.log("Direct Groth16 verification (dummy proof):", valid);
    }
}
