export const PREDICTION_MARKET_ABI = [
  {
    type: "function",
    name: "nextMarketId",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextBetId",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalVolume",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMarketCore",
    inputs: [{ name: "marketId", type: "uint256" }],
    outputs: [
      { name: "gameId", type: "uint256" },
      { name: "agentId", type: "uint256" },
      { name: "mType", type: "uint8" },
      { name: "status", type: "uint8" },
      { name: "outcome", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMarketPools",
    inputs: [{ name: "marketId", type: "uint256" }],
    outputs: [
      { name: "totalPool", type: "uint256" },
      { name: "yesPool", type: "uint256" },
      { name: "noPool", type: "uint256" },
      { name: "lockTime", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMarketOdds",
    inputs: [{ name: "marketId", type: "uint256" }],
    outputs: [
      { name: "yesOdds", type: "uint256" },
      { name: "noOdds", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMarketStats",
    inputs: [{ name: "marketId", type: "uint256" }],
    outputs: [
      { name: "totalBets", type: "uint256" },
      { name: "totalPool", type: "uint256" },
      { name: "yesOdds", type: "uint256" },
      { name: "noOdds", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserBets",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBet",
    inputs: [{ name: "betId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "bettor", type: "address" },
          { name: "marketId", type: "uint256" },
          { name: "prediction", type: "bool" },
          { name: "amount", type: "uint256" },
          { name: "claimed", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "canClaimBet",
    inputs: [{ name: "betId", type: "uint256" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "calculatePotentialPayout",
    inputs: [
      { name: "marketId", type: "uint256" },
      { name: "prediction", type: "bool" },
      { name: "betAmount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "placeBet",
    inputs: [
      { name: "marketId", type: "uint256" },
      { name: "prediction", type: "bool" },
    ],
    outputs: [{ name: "betId", type: "uint256" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "claimPayout",
    inputs: [{ name: "betId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "markets",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "gameId", type: "uint256" },
      { name: "agentId", type: "uint256" },
      { name: "marketType", type: "uint8" },
      { name: "targetValue", type: "uint256" },
      { name: "status", type: "uint8" },
      { name: "outcome", type: "bool" },
      { name: "createdAt", type: "uint256" },
      { name: "lockTime", type: "uint256" },
      { name: "totalPool", type: "uint256" },
      { name: "yesPool", type: "uint256" },
      { name: "noPool", type: "uint256" },
    ],
    stateMutability: "view",
  },
] as const;
